name: Deploy

on:
  pull_request:

jobs:
  build_and_preview_protocol:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: yarn
      - run: yarn protocol:build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_MSTABLE_APPS_PROTOCOL }}"
          expires: 30d
          projectId: mstable-apps-protocol
          entryPoint: apps/protocol/firebase.json
          target: mstable-apps-protocol
